# fhv_tripdata_2015/2016

In [10]:
# fetch fhv_tripdata_2015/2016

import csv
import sqlite3
import pandas as pd

conn = sqlite3.connect('uber_sample.db')
cur = conn.cursor()

for y in range (5, 7):
    
    cur.execute('DROP TABLE IF EXISTS fhv_tripdata_201' + str(y))
    cur.execute('CREATE TABLE fhv_tripdata_201' + str(y) + '(Dispatching_base_num TEXT, Pickup_date TEXT, locationID INTEGER)')
    
    for m in range (1, 13):

        if m < 10:
            m = "0" + str(m)
        else:
            m = str(m)

        url = 'fhv_tripdata_201' + str(y) + '-' + m + '_s.csv'
        #url = 'https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-01.csv'
        print(url)

        try:
            df = pd.read_csv(url)

        except:
            continue

        else:

            data = df.transpose().to_dict().values()

            for i in data:
                cur.execute('INSERT INTO fhv_tripdata_2015 (Dispatching_base_num, Pickup_date, locationID) VALUES (?, ?, ?)', 
                            (i['Dispatching_base_num'], i['Pickup_date'], i['locationID']))
          
conn.commit()
cur.close()

fhv_tripdata_2015-01_s.csv
fhv_tripdata_2015-02_s.csv
fhv_tripdata_2015-03_s.csv
fhv_tripdata_2015-04_s.csv
fhv_tripdata_2015-05_s.csv
fhv_tripdata_2015-06_s.csv
fhv_tripdata_2015-07_s.csv
fhv_tripdata_2015-08_s.csv
fhv_tripdata_2015-09_s.csv
fhv_tripdata_2015-10_s.csv
fhv_tripdata_2015-11_s.csv
fhv_tripdata_2015-12_s.csv
fhv_tripdata_2016-01_s.csv
fhv_tripdata_2016-02_s.csv
fhv_tripdata_2016-03_s.csv
fhv_tripdata_2016-04_s.csv
fhv_tripdata_2016-05_s.csv
fhv_tripdata_2016-06_s.csv
fhv_tripdata_2016-07_s.csv
fhv_tripdata_2016-08_s.csv
fhv_tripdata_2016-09_s.csv
fhv_tripdata_2016-10_s.csv
fhv_tripdata_2016-11_s.csv
fhv_tripdata_2016-12_s.csv

# hourly count

In [32]:
# fhv_tripdata_hourly_count

import csv
import sqlite3
import pandas as pd
import math

conn = sqlite3.connect('uber_sample.db')
cur = conn.cursor()

for y in range (5, 7):
    
    cur.execute('DROP TABLE IF EXISTS fhv_tripdata_hourly')
    cur.execute('CREATE TABLE fhv_tripdata_hourly (Dispatching_base_num TEXT, Pickup_time TEXT, locationID INTEGER ,count INTEGER)')
    
    for m in range (1, 13):

        if m < 10:
            m = "0" + str(m)
        else:
            m = str(m)

        url = 'fhv_tripdata_201' + str(y) + '-' + m + '_s.csv'
        #url = 'https://s3.amazonaws.com/nyc-tlc/trip+data/fhv_tripdata_2015-01.csv'
        print(url)

        try:
            df = pd.read_csv(url)

        except:
            continue

        else:

            data = df.transpose().to_dict().values()

            for i in data:
                
                base = i['Dispatching_base_num']
                time_pieces = i['Pickup_date'].split(":")
                time = time_pieces[0]
                loc = i['locationID']
                
                if math.isnan(loc):
                    loc = 999
                
                cur.execute('''SELECT count FROM fhv_tripdata_hourly 
                            WHERE Dispatching_base_num = ?  AND Pickup_time = ? and locationID = ?''', 
                            (base, time, loc))
                row = cur.fetchone()
                
                if row is None:
                    cur.execute('''INSERT INTO fhv_tripdata_hourly (Dispatching_base_num, Pickup_time, locationID, count)
                                VALUES (?, ?, ?, 1)''', (base, time, loc))
                    
                else:
                    cur.execute('''UPDATE fhv_tripdata_hourly SET count = count + 1 
                                WHERE Dispatching_base_num = ?  AND Pickup_time = ? AND locationID = ?''',
                                (base, time, loc))

          
conn.commit()
cur.close()

fhv_tripdata_2015-01_s.csv
fhv_tripdata_2015-02_s.csv
fhv_tripdata_2015-03_s.csv
fhv_tripdata_2015-04_s.csv
fhv_tripdata_2015-05_s.csv
fhv_tripdata_2015-06_s.csv
fhv_tripdata_2015-07_s.csv
fhv_tripdata_2015-08_s.csv
fhv_tripdata_2015-09_s.csv
fhv_tripdata_2015-10_s.csv
fhv_tripdata_2015-11_s.csv
fhv_tripdata_2015-12_s.csv
fhv_tripdata_2016-01_s.csv
fhv_tripdata_2016-02_s.csv
fhv_tripdata_2016-03_s.csv
fhv_tripdata_2016-04_s.csv
fhv_tripdata_2016-05_s.csv
fhv_tripdata_2016-06_s.csv
fhv_tripdata_2016-07_s.csv
fhv_tripdata_2016-08_s.csv
fhv_tripdata_2016-09_s.csv
fhv_tripdata_2016-10_s.csv
fhv_tripdata_2016-11_s.csv
fhv_tripdata_2016-12_s.csv